- name: edit grub config
  hosts: test
  become: yes
  tasks:
  - name: edit grub config
    lineinfile:
     path: /etc/default/grub
     regexp: '^GRUB_CMDLINE_LINUX'
     line: 'GRUB_CMDLINE_LINUX="no_timer_check console=tty0 console=ttyS0,115200n8 net.ifnames=0 biosdevname=0 elevator=noop"'
     state: present

  - name: run grub2-mkconfig
    command:
     cmd: grub2-mkconfig -o /etc/default/grub
