- name: edit grub config
  hosts: test
  become: yes
  tasks:
  - name: add net.ifnames=0
    lineinfile:
      path: /etc/default/grub
      backrefs: yes
      regexp: '^(GRUB_CMDLINE_LINUX=(?!.* net.ifnames)\"[^\"]+)(\".*)'
      line: '\1 net.ifnames=0\2'

  - name: add biosdevname=0
    lineinfile:
      path: /etc/default/grub
      backrefs: yes
      regexp: '^(GRUB_CMDLINE_LINUX=(?!.* biosdevname)\"[^\"]+)(\".*)'
      line: '\1 biosdevname=0\2'

  - name: run grub2-mkconfig
    command:
     cmd: grub2-mkconfig -o /boot/grub2/grub.cfg

